<?php

declare(strict_types=1);

use App\Rules\SlugRule;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Str;

covers(SlugRule::class);

uses()->group('rules');

function slugRuleFails(mixed $value): bool
{
    $failed = false;

    (new SlugRule())->validate('url_handle', $value, function () use (&$failed): void {
        $failed = true;
    });

    return $failed;
}

test('passes for a valid slug', function (string $value) {
    expect(slugRuleFails($value))->toBeFalse();
})->with(['a', '2024', 'new-product', 'summer-sale-2024', 'x-1-y-2']);

test('fails for a value that is not a valid slug', function (mixed $value) {
    expect(slugRuleFails($value))->toBeTrue();
})->with([
    'uppercase' => ['New-Product'],
    'space' => ['new product'],
    'comma' => ['shirt,red'],
    'colon' => ['shirt:red'],
    'slash' => ['shirt/red'],
    'underscore' => ['new_product'],
    'leading hyphen' => ['-new-product'],
    'trailing hyphen' => ['new-product-'],
    'double hyphen' => ['new--product'],
    'accented letter' => ['café'],
    'empty string' => [''],
    'not a string' => [['new-product']],
]);

test('blank values never reach the rule through the validator', function (string $value) {
    $validator = Validator::make(
        ['url_handle' => $value],
        ['url_handle' => ['nullable', 'string', 'max:255', new SlugRule()]],
    );

    expect($validator->fails())->toBeFalse();
})->with(['', '   ']);

test('passes for handles generated by the slug helper', function (string $title) {
    expect(slugRuleFails(Str::slug($title)))->toBeFalse();
})->with([
    'Hello World',
    'Café Latté',
    'Product #1 -- 50% off',
    '  spaced  ',
    'under_score',
    'T-Shirt (Red/Blue)',
]);
