import {
    type LucideIcon,
    AwardIcon,
    CheckIcon,
    CircleCheckIcon,
    ClockIcon,
    CreditCardIcon,
    DollarSignIcon,
    FlameIcon,
    GiftIcon,
    GlobeIcon,
    HandshakeIcon,
    HeadphonesIcon,
    HeartIcon,
    LeafIcon,
    LightbulbIcon,
    LockIcon,
    MailIcon,
    MapPinIcon,
    MessageCircleIcon,
    PackageIcon,
    PercentIcon,
    PhoneIcon,
    RefreshCwIcon,
    RotateCcwIcon,
    ShieldCheckIcon,
    SmileIcon,
    SparklesIcon,
    StarIcon,
    TagIcon,
    ThumbsUpIcon,
    TruckIcon,
    UsersIcon,
    WalletIcon,
    ZapIcon,
} from 'lucide-react';

import type { IconName } from './names';

export type IconComponent = LucideIcon;

export const LUCIDE_ICONS: Record<IconName, IconComponent> = {
    shipping: TruckIcon,
    package: PackageIcon,
    globe: GlobeIcon,
    location: MapPinIcon,
    lightning: ZapIcon,
    clock: ClockIcon,
    refresh: RefreshCwIcon,
    returns: RotateCcwIcon,
    support: HeadphonesIcon,
    chat: MessageCircleIcon,
    phone: PhoneIcon,
    email: MailIcon,
    shield: ShieldCheckIcon,
    lock: LockIcon,
    verified: CircleCheckIcon,
    check: CheckIcon,
    card: CreditCardIcon,
    wallet: WalletIcon,
    money: DollarSignIcon,
    tag: TagIcon,
    discount: PercentIcon,
    star: StarIcon,
    award: AwardIcon,
    sparkles: SparklesIcon,
    fire: FlameIcon,
    'thumbs-up': ThumbsUpIcon,
    community: UsersIcon,
    handshake: HandshakeIcon,
    smile: SmileIcon,
    heart: HeartIcon,
    gift: GiftIcon,
    eco: LeafIcon,
    idea: LightbulbIcon,
};
