import fs from 'fs';
import path from 'path';

import picocolors from 'picocolors';
import { type PluginContext } from 'rolldown';
import { type HmrContext, type Plugin } from 'vite';

import { adminThemes, getTheme } from '../lib/admin-theme-config.ts';
import { contrastRatio, type Oklch } from '../lib/color.ts';
import { type ThemeColors } from '../types/theme.ts';

const AA_TEXT = 4.5;
const AA_NON_TEXT = 3;

const TEXT_PAIRS: [keyof ThemeColors, keyof ThemeColors][] = [
    ['foreground', 'background'],
    ['foreground', 'card'],
    ['foreground', 'popover'],
    ['foreground', 'muted'],
    ['foreground', 'accent'],
    ['foreground', 'sidebar'],
    ['mutedForeground', 'background'],
    ['mutedForeground', 'card'],
    ['mutedForeground', 'muted'],
    ['mutedForeground', 'accent'],
    ['mutedForeground', 'sidebar'],
    ['secondaryForeground', 'secondary'],
    ['accentForeground', 'accent'],
    ['primaryForeground', 'primary'],
    ['sidebarForeground', 'sidebar'],
    ['sidebarPrimaryForeground', 'sidebarPrimary'],
    ['sidebarAccentForeground', 'sidebarAccent'],
    ['primary', 'background'],
    ['primary', 'card'],
    ['primary', 'muted'],
    ['primary', 'accent'],
    ['destructive', 'background'],
    ['destructive', 'card'],
    ['destructive', 'muted'],
    ['destructive', 'accent'],
];

const NON_TEXT_PAIRS: [keyof ThemeColors, keyof ThemeColors][] = [
    ['chart1', 'background'],
    ['chart2', 'background'],
    ['chart3', 'background'],
    ['chart4', 'background'],
    ['chart5', 'background'],
];

interface AdminThemesOptions {
    fallbackTheme?: string;
    phpOutputFile?: string;
    cssOutputFile?: string;
}

export default function adminThemesPlugin({
    fallbackTheme = 'neutral',
    phpOutputFile = 'config/admin-themes.php',
    cssOutputFile = 'resources/css/admin-theme.css',
}: AdminThemesOptions = {}): Plugin {
    const absolutePhpFile = path.resolve(phpOutputFile);
    const absoluteCssFile = path.resolve(cssOutputFile);
    const watched = ['resources/js/lib/admin-theme-config.ts', 'resources/js/lib/color.ts'].map((file) =>
        path.resolve(file),
    );

    let context: PluginContext;

    const generate = (failOnViolation: boolean) => {
        const violations = auditContrast();

        if (violations.length > 0) {
            const message = `Admin themes violate WCAG AA:\n${violations.join('\n')}`;

            if (failOnViolation) {
                context.error(message);
            }

            context.warn(message);
        }

        fs.writeFileSync(absolutePhpFile, renderPhp(), 'utf8');
        fs.writeFileSync(absoluteCssFile, renderCss(fallbackTheme), 'utf8');

        context.info(
            'Admin themes generated: ' +
                picocolors.dim(
                    `${path.relative(process.cwd(), absolutePhpFile)}, ${path.relative(process.cwd(), absoluteCssFile)}`,
                ),
        );
    };

    return {
        name: 'admin-themes',

        buildStart(): void {
            context = this satisfies PluginContext;

            generate(true);
        },

        handleHotUpdate(ctx: HmrContext): void {
            if (watched.includes(ctx.file)) {
                generate(false);
            }
        },
    };
}

function cssVariableName(token: string): string {
    return `--${token
        .replace(/([A-Z])/g, '-$1')
        .toLowerCase()
        .replace(/chart(\d)/, 'chart-$1')}`;
}

function parseOklch(value: string): Oklch {
    const match = value.match(/oklch\(([\d.]+) ([\d.]+) ([\d.]+)\)/);

    if (!match) {
        throw new Error(`Unparsable colour: ${value}`);
    }

    return { l: Number(match[1]), c: Number(match[2]), h: Number(match[3]) };
}

function auditContrast(): string[] {
    const violations: string[] = [];

    for (const { name } of adminThemes) {
        const theme = getTheme(name);

        for (const mode of ['light', 'dark'] as const) {
            const colors = theme[mode];

            const check = (pairs: [keyof ThemeColors, keyof ThemeColors][], minimum: number) => {
                for (const [a, b] of pairs) {
                    const ratio = contrastRatio(parseOklch(colors[a]), parseOklch(colors[b]));

                    if (ratio < minimum) {
                        violations.push(`  ${name}/${mode}: ${a} on ${b} is ${ratio.toFixed(2)}:1, needs ${minimum}:1`);
                    }
                }
            };

            check(TEXT_PAIRS, AA_TEXT);
            check(NON_TEXT_PAIRS, AA_NON_TEXT);
        }
    }

    return violations;
}

function renderPhp(): string {
    const lines = [
        '<?php',
        '',
        'declare(strict_types=1);',
        '',
        '// Auto-generated by vite plugin.',
        '// DO NOT EDIT MANUALLY!',
        '',
        'return [',
    ];

    for (const { name } of adminThemes) {
        const theme = getTheme(name);
        lines.push(`    '${name}' => [`);

        for (const mode of ['light', 'dark'] as const) {
            lines.push(`        '${mode}' => [`);

            for (const [token, value] of Object.entries(theme[mode])) {
                lines.push(`            '${cssVariableName(token).slice(2)}' => '${value}',`);
            }

            lines.push('        ],');
        }

        lines.push('    ],');
    }

    lines.push('];', '');

    return lines.join('\n');
}

function renderCss(fallbackTheme: string): string {
    const theme = getTheme(fallbackTheme as Parameters<typeof getTheme>[0]);

    const block = (selector: string, colors: ThemeColors) =>
        [
            `${selector} {`,
            ...Object.entries(colors).map(([token, value]) => `    ${cssVariableName(token)}: ${value};`),
            '}',
        ].join('\n');

    return [
        '/**',
        ' * Auto-generated by vite plugin.',
        ' * DO NOT EDIT MANUALLY!',
        ' */',
        '',
        block(':root', theme.light),
        '',
        block('.dark', theme.dark),
        '',
    ].join('\n');
}
