import fs from 'fs';
import path from 'path';

import picocolors from 'picocolors';
import { type PluginContext } from 'rolldown';
import { type HmrContext, type Plugin } from 'vite';

let context: PluginContext;

const BUNDLES = ['common', 'admin', 'storefront'] as const;

interface TranslationTypesOptions {
    langDir?: string;
    outputDir?: string;
    outputFileName?: string;
    defaultLocale?: string;
}

export default function translationTypes({
    langDir = 'lang',
    outputDir = 'resources/js/types',
    outputFileName = 'translations.ts',
    defaultLocale = 'en',
}: TranslationTypesOptions = {}): Plugin {
    const absoluteLangDir = path.resolve(langDir);
    const absoluteOutputDir = path.resolve(outputDir);
    const absoluteOutputFile = path.join(absoluteOutputDir, outputFileName);

    return {
        name: 'translation-types',

        buildStart(): void {
            context = this satisfies PluginContext;

            if (!fs.existsSync(absoluteOutputDir)) {
                fs.mkdirSync(absoluteOutputDir, { recursive: true });
            }

            generateTranslationTypes(absoluteLangDir, absoluteOutputFile, defaultLocale);
        },

        handleHotUpdate(ctx: HmrContext): void | Promise<void> {
            if (ctx.file.startsWith(absoluteLangDir + path.sep) && ctx.file.endsWith('.json')) {
                generateTranslationTypes(absoluteLangDir, absoluteOutputFile, defaultLocale);
            }
        },
    };
}

function generateTranslationTypes(langDir: string, outputFile: string, defaultLocale: string): void {
    try {
        const translations: Record<string, string> = {};

        for (const bundle of BUNDLES) {
            const bundleFile = path.join(langDir, bundle, `${defaultLocale}.json`);

            if (!fs.existsSync(bundleFile)) {
                context.warn(
                    'Translation bundle not found: ' + picocolors.dim(path.relative(process.cwd(), bundleFile)),
                );
                continue;
            }

            Object.assign(translations, JSON.parse(fs.readFileSync(bundleFile, 'utf8')));
        }

        fs.writeFileSync(outputFile, generateTypesContent(translations), 'utf8');

        context.info('Types generated: ' + picocolors.dim(path.relative(process.cwd(), outputFile)));
    } catch (error) {
        const errorMessage = error instanceof Error ? error.message : String(error);

        context.warn(errorMessage);
    }
}

function generateTypesContent(translations: Record<string, string>): string {
    const translationsWithParams = extractTranslationsWithParams(translations);

    const interfaceContent = `/**
 * Auto-generated by vite plugin.
 * DO NOT EDIT MANUALLY!
 */

interface Translations {
${generateTranslationsInterface(translationsWithParams)}
}

export type TranslationKey = keyof Translations;
export type TranslationParams<K extends TranslationKey> = Translations[K] extends string ? Record<string, never> : Translations[K];
`;

    return interfaceContent;
}

function extractTranslationsWithParams(
    translations: Record<string, string>,
): Record<string, string | Record<string, string>> {
    const result: Record<string, string | Record<string, string>> = {};

    for (const [key, value] of Object.entries(translations)) {
        const paramMatches = value.match(/:(\w+)/g);

        if (paramMatches && paramMatches.length > 0) {
            const params: Record<string, string> = {};

            paramMatches.forEach((match) => {
                const paramName = match.substring(1); // Remove the : prefix

                params[paramName] = 'string | number';
            });

            result[key] = params;
        } else {
            result[key] = value;
        }
    }

    return result;
}

function generateTranslationsInterface(translations: Record<string, string | Record<string, string>>): string {
    let result = '';

    for (const [key, value] of Object.entries(translations)) {
        const escapedKey = key.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/"/g, '\\"').replace(/\n/g, '\\n');

        if (typeof value === 'string') {
            result += `    '${escapedKey}': string;\n`;
        } else {
            const paramsObject = Object.keys(value)
                .map((param) => `        ${param}: string | number;`)
                .join('\n');

            result += `    '${escapedKey}': {\n${paramsObject}\n    };\n`;
        }
    }

    return result.trimEnd();
}
